"use strict";
exports.__esModule = true;
var produto_1 = require("./produto");
var item_1 = require("./item");
var compra_1 = require("./compra");
var cliente_1 = require("./cliente");
var p1 = new produto_1.Produto("Notebook", 2590.70);
var p2 = new produto_1.Produto("Tv 40", 3466);
var p3 = new produto_1.Produto("Caneta", 2.30);
var p4 = new produto_1.Produto("Caderno", 15.80);
var p5 = new produto_1.Produto("Fogão", 1550.98);
var p6 = new produto_1.Produto("Geladeira", 1764.50);
var i1 = new item_1.Item(p1, 1);
var i2 = new item_1.Item(p2, 1);
var i3 = new item_1.Item(p3, 4);
var i4 = new item_1.Item(p4, 2);
var i5 = new item_1.Item(p5, 1);
var i6 = new item_1.Item(p6, 1);
var c1 = new compra_1.Compra("Amazon");
var c2 = new compra_1.Compra("Americanas");
var c3 = new compra_1.Compra("Magazine Luiza");
var guilherme = new cliente_1.Cliente("Guilherme");
c1.addItem(i1);
c2.addItem(i2);
c2.addItem(i3);
c2.addItem(i4);
c3.addItem(i5);
c3.addItem(i6);
guilherme.addCompra(c1);
guilherme.addCompra(c2);
guilherme.addCompra(c3);
console.log(guilherme.listarCompras());
